### ISSUE TITLE
Emails to Recruit for Reviewers

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#10]
[Copy doc](https://docs.google.com/document/d/1yfzdO2PojYhoOzBU_8SR-RMhgigSe3oodqIE_xvuA5U/edit#) 

- [x] Write up a pitch to recruit reviewers
- [x] Review @couci 
- [x] Review @mikehenrty 
- [x] Create a "register as a reviewer form" 
- [x] Review @couci 
- [x] Review @mikehenrty 

- [x] Send to:  
** REPS [x] @couci 
** L10N mailing list [ ] @nukeador

**Comment by mikehenrty** [comment]
reviewed recruiting email (for both MDM and L10N0) and reviewed "register to be a reviewer" form

**Comment by couci** [comment]
E-mail to mozillians via salesforce sent

**Comment by couci** [comment]
Reps sent done, discourse posts up
@nukeador when are you planning to send to l10n drivers?

**Comment by nukeador** [comment]
Can you run the copy with Jeff on Monday? I didn't know we wanted to send this now and I guess the copy for l10n communities should be different. 

I can check on Tuesday.

**Comment by couci** [comment]
ok I am sending an e-mail to Jeff today

**Comment by couci** [comment]
e-mail to Jeff sent, waiting for a reply

**Comment by couci** [comment]
Jeff, gave the thumbs-up I am sending it to the mailing list provided and he will also send to irc.

This can now be closed
