### ISSUE TITLE
Prepare the reporting form for Fenix campaign

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#146]
- [x] Have the draft with fields ready
- [x] Get the form approved by the Fenix team
- [x] have the form ready online

**Comment by couci** [comment]
@michaelkohler here is the draft of the report https://docs.google.com/document/d/1s-zMmugJ_CkI-AoCtBRqL1bWyMmU1HudITvZT1vZK6I/edit?ts=5ca4fb72#

**Comment by couci** [comment]
form is online we are ready to go

**Comment by MichaelKohler** [comment]
you are aware of the fact that screenshots can't be uploaded in Fenix, right? https://github.com/mozilla-mobile/fenix/issues/1467

**Comment by MichaelKohler** [comment]
.. and that we will need a separate repo? https://github.com/mozilla/oi-fenix-campaign/issues/5

**Comment by MichaelKohler** [comment]
and do we have the subdomain?

**Comment by couci** [comment]
The subdomain for the form you mean? I thought that has been given based on the last comment from nemo.
I will comment separately for the repo on the issue. As for the bug, well it's not in our end it's rather on the fenix team. If it doesn't get resolved we take the screenshots part away from the form
