### ISSUE TITLE
Redo activity template

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#153]
@LucyeoH to talk with Rina and Megan on internal resourcing

* Need Interaction Design: Revisit template to design something that works better for both audiences: mobilizers, and individual contributors. 
* Could include: Revisit sidebar and tone to be more contributor-centric, need prominent “immediate action” buttons for people who aren’t going to run events.

**Comment by LucyeoH-zz** [comment]
Email sent will follow-up next week!

**Comment by couci** [comment]
template is here: https://docs.google.com/document/d/1PK1w1LRs52sX5MByvGt7GdqN2lOYT-_8g7SYaAjhKq8/edit?folder=0B3CuegKgwkKkflFuUElIaHp2T0xtNTUxeTRFMGJmc0FRYmZyTXFSRkRFTU82Yk5uSmFQSTA#
