### ISSUE TITLE
Accounts Strategy Alignment 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#161]
## Project title: 
Accounts Alignment 
## Project owner: 
Lucy & Konstantina
## Stakeholders for Sign-Off: 
Lucile, Patrick McClard
## Background:
Ensuring our community members has a strong understanding of our accounts strategy and how and why it's critical to the mission so they feel confident and comfortable speaking to it and representing it. 

## Outreach Plan:
* Email 
* Resources 
* AMA with Mitchell & Chris More?

**Comment by couci** [comment]
@LucyeoH any news on this one?

**Comment by couci** [comment]
this will be launched after Skyline (October 22nd)

New target date October 28th

**Comment by couci** [comment]
An AMA is not necessary, the next step is a report here
