### ISSUE TITLE
Close Fenix campaign bug report

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#162]
We need to close the Fenix campaign bug report and redirect people to the Fenix repo: https://github.com/mozilla-mobile/fenix/issues/new/choose

There should be a message saying: The bughunting campaign is now over, if you have a Preview bug please report it here [link]

**Comment by couci** [comment]
@MichaelKohler can you take over this one?

**Comment by MichaelKohler** [comment]
Done: https://bughunterissues.mozilla.community/
