### ISSUE TITLE
Create form for the syncfest campaign

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#168]
Create a form that will connect to a new private repo for the firefox syncfest campaign

**Comment by couci** [comment]
Draft can be found here: https://docs.google.com/document/d/1iuEfM3z0pIQZTqbZ3GLwYH2-L89m1zl8_bGkfF6SQks/edit# (internally shared for now)

**Comment by MichaelKohler** [comment]
Repo: https://github.com/mozilla/syncfest-campaign
Issues Repo: https://github.com/MichaelKohler/syncfest-test/issues
Test Instance: https://mozilla-syncfest-test.herokuapp.com

**Comment by couci** [comment]
Thanks @MichaelKohler this looks good. I will send it over to the syncfest team and ask them to file bugs at the repo.
