### ISSUE TITLE
Check firefox voice page for bugs

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#172]
Make sure that the https://events.mozilla.org/firefoxvoicecampaign page has no bugs before the launch

**Comment by Francescaminelli** [comment]
Hi, 
The  document that give instruction on how to install the addon gives three ways for people to report issues with installation. It might be better to direct them to the feedback form. The link to the document is here: https://docs.google.com/document/d/1nTyIw4G1yWnxlTmJ-Nvs9OIDntAIYmRPMLKVJZ9TxkI/edit  . The part that should be changed is at then end of the document.

**Comment by couci** [comment]
bugs fixed, this can be closed
