### ISSUE TITLE
Email for feature prioritization Firefox Voice Campaign

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/CampaignsforMDM#177]
- [x] Agree on copy  @harraton
- [x] Agree on who to sent @harraton @awallin   
- [ ] Load email
- [ ] Send email

**Comment by couci** [comment]
Agreed on the copy, we are discussing when to send the e-mail. @Francescaminelli will send it once the date is agreed.

**Comment by awallin** [comment]
I'd like to send it this week to re-engage the first cohort before the holidays. Thursday Dec 19?

**Comment by couci** [comment]
That works for us since the second cohort isn't as big.
@Francescaminelli please load the e-mail at splash from here: https://docs.google.com/document/d/1D5Wq4zReUu9I0CTDK79u0MwLiunxJbmt2WGwrwM_bhY/edit#heading=h.pqlkc0uo8dku
