### ISSUE TITLE
Thank you for volunteers 

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/CampaignsforMDM#178]
- [x] Create copy for a thank you for volunteers underlining everything that has been achieved with their help this year. 

- [ ] Post it on discourse

**Comment by couci** [comment]
We are working here: https://docs.google.com/document/d/1IFm6qhdpWDqKxND9Sauq1B4zAXcsYbXwDzYK8CZbCOk/edit?folder=1fq884mqC7LohyUEcS1uFCyF0dg1d6Fat
