### ISSUE TITLE
Create SUMO activity in Activate - Create proposal

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/CampaignsforMDM#183]
Create a proposal for a SUMO activity in activate

- [x] request data from Madalina on 2 star and 3 star reviews
- [x] create a proposal with goals based on the template
- [x] ask feedback for the proposal from @rkelimuttu and Giulia
- [x] send the proposal to Madalina for final go/not go
- [x] get it ready for the new portal

**Comment by couci** [comment]
Template lives here: https://docs.google.com/document/d/1-FIG3Lx8jczB1Iqz6ONUPsnlpEY7UIJl5u2p0MXcNto/edit

We need to arrange a meeting with Giulia and Kiki to see if they are alligned

**Comment by couci** [comment]
3 proposals have been sent to the SUMO team:
- respond to questions
- documentation
- translation

we will pass them in the portal
