### ISSUE TITLE
Move content from splash to portal

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#205]

**Comment by couci** [comment]
- [x] make a list of all past campaigns @Francescaminelli 
- [x] evaluate which ones we want to pass to the new community portal @Francescaminelli @couci 
- [x] get text from splash in docs @couci @Francescaminelli 
- [x] pass them at the new community portal @Francescaminelli

**Comment by Francescaminelli** [comment]
List of Past Campaigns: https://docs.google.com/document/d/1VtgdMqL5vYPoAQaGjetUnXZhppWmsrRG796guL8nDnY/edit?usp=sharing

**Comment by couci** [comment]
We are still blocked on the Firefox Voice. Since the team wants the email connection we will pass it as a campaign.
Waiting for playground to have the email integration ready before we pass Firefox Voice
