### ISSUE TITLE
Turn Firefox Voice campaign to an evergreen activity

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#206]
- [x] populate firefox voice campaign into activate template @Francescaminelli 
- [x] create event activity @Francescaminelli @couci 
- [x] work with the Firefox Voice team to create an experiment for volunteers devs

**Comment by Francescaminelli** [comment]
Firefox voice campaign in activate template: 

https://docs.google.com/document/d/15uYoHo3nw0EaVHND8JPoBw-28FgmjZ5AWwjNhTLq7Ic/edit
