### ISSUE TITLE
Prepare for campaign interviews to TL;DR series

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#213]
- [x] prepare interview guide @Francescaminelli 
- [x] decide which teams we will speak to @couci @Francescaminelli @LucyeoH 
- [x] arrange times with the teams @couci @LucyeoH

**Comment by Francescaminelli** [comment]
Interview guide here: https://docs.google.com/document/d/1m4BxkfjZGpAhXh-gAAn9W3NmwPo3z4HYMlwWQBoFAh0/edit

Step-by-step interview process: https://docs.google.com/document/d/1VydxPxTUMflQE0lGFhkRdWkBoub90pwIALKdVwSiSHo/edit

**Comment by couci** [comment]
all emails have been sent, waiting for replies
