### ISSUE TITLE
Have everything prepared for the FIrefox Sync campaign

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#214]
- [x] pass the copy to the new community portal
- [ ] talk with the team on launching days
- [x] recheck the testing cases, send to softvision
- [x] make sure reporting form is ready (private repo + form updates)

**Comment by MichaelKohler** [comment]
I've updated the form to work with a private repo. Once you have a private repo I can link that one to the form.

**Comment by MichaelKohler** [comment]
The form now lives at https://mozilla-syncfest.herokuapp.com (I've removed the -test). Also I just remembered we already have a repo, we can just use that one and make it private: https://github.com/mozilla/syncfest-volunteersbugs/issues
