### ISSUE TITLE
Addendum "I Pledge" Campaign 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#24]
Mitchell would like to empower Mozillians to use the Mozilla Addendum. 

Perhaps as a pledge to sign up to honor these principles in their work and help others understand and use them. Or perhaps to do an action in their communities that advances the principles. 

To be explored.

**Comment by couci** [comment]
Currently we don't see huge engagement potential on this one so we keep it on the backlog for Q3

**Comment by couci** [comment]
By discussing this we realized that 1) explaining the meaning of addendum to  mozillians will be hard thus the engagement won't be hight
2) there is no learning opportunity to volunteers rather the feeling of contributing to Mozilla's greater good. 
For the above reason I am closing this one
