### ISSUE TITLE
Create documentation for the event

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#39]
- [x] Create documentation to be shared with volunteers
- [x] Upload it in the website

**Comment by mikehenrty** [comment]
Here is the draft for the "sentence collection" documentation: https://docs.google.com/document/d/1zYu2vq4Rxdyib1m95pZ-tDuawQDdqSUeOdtCubul_WE/edit

**Comment by couci** [comment]
Documentation is up here: https://voice-sprint.mozilla.community/
