### ISSUE TITLE
Thank You Notes

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#40]
- [x] Customize & send
- [ ] put on discourse 

Hi X,

Thank you so much for participating in the Common Voice Global Sprint thanks to your contributions we added more than 21,000 new sentences to Common Voice in more than 24 different languages. 

Soon we'll be able to start collecting voice data in these languages, making common voice an even more international tool to keep the web open. 

Don't want to stop? You can keep contributing sentences in your language here :  [link]

More amazing contribution opportunities are coming soon! From June 2nd - June 9th we'll be creating a new way for you to support Firefox Users on the Google Playstore. We're calling it the Fantastic Firefox Support Sprint. Read all about it on discourse here, and start planning your next great contribution event!

Thanks again to everyone for donating your time and sentences to help keep the web open!

You rock!!

Konstantina

**Comment by couci** [comment]
Discourse isn't needed for personal emails, this has been sent.
