### ISSUE TITLE
Parsys support for the SuMo campaign

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#46]
- [x] get microwebsite hosted under mozilla.community
- [ ] get infra to set up community analytics for both of the tool and microwebsite
- [x] get tool hosted under mozilla.community

**Comment by couci** [comment]
microwebsite and tool urls have been created,

need to check on the google analytics

**Comment by MichaelKohler** [comment]
GA is done as well: https://github.com/mozilla/parsys/issues/361

**Comment by couci** [comment]
cool, I will ensure that also the tool is in there and will close this one
