### ISSUE TITLE
Pocket community curation pilot

### ISSUE THREAD

**Issue by nukeador** [mozilla/CampaignsforMDM#51]
Explore how the current process is and benchmarking (editorial vs community) for en-US and de-DE

**Comment by nukeador** [comment]
Waiting to sync with Pocket team, we might want to advance a conversation Q3 and do somthing Q4.

**Comment by couci** [comment]
Moving this into exploration @nukeador you're responsible on driving the conversations and keep us updated

**Comment by couci** [comment]
@nukeador what is the update here?

**Comment by nukeador** [comment]
Still under exploration.

**Comment by couci** [comment]
@nukeador is meeting with the team this week. Based on the feedback he brings back, we will discuss on Monday 21st next steps on this one (forming a campaign or putting this to backlog)

**Comment by couci** [comment]
We are moving forward with this idea, turning this into epic to start planning
