### ISSUE TITLE
Pocket support localization

### ISSUE THREAD

**Issue by nukeador** [mozilla/CampaignsforMDM#53]

**Comment by nukeador** [comment]
Waiting for syn with SUMO team.

**Comment by nukeador** [comment]
Content will be moving to SUMO site, we will sync end of August on progress and see if there is a need for a sprint/campaign

**Comment by couci** [comment]
Moving this on exploration @nukeador once you hear back from the team please update

**Comment by LucyeoH-zz** [comment]
George says this is seen as "non-valuable" b/c there's not a worry thinks won't be localized

**Comment by couci** [comment]
@nukeador did we get any update on this? If not should this be closed?

**Comment by nukeador** [comment]
No decisions has been made yet, I'm in contact with Justin from Pocket to know more. Currently this is "waiting/on hold"

**Comment by couci** [comment]
@nukeador should we close this one?

**Comment by nukeador** [comment]
This has yet to be defined I guess, we can move it to the icebox for the future.
