### ISSUE TITLE
Marketing Support campaign

### ISSUE THREAD

**Issue by nukeador** [mozilla/CampaignsforMDM#55]
Initial idea was to run a campaign around supporting the launch of Firefox 63.

- Launch date: October 24th

However feedback from marketing team suggests this timeline is not particularly important. Therefore considering other ideas...

## Ideas

- Localization coordination with SUMO and L10N: Specially around updated SUMO docs and moz.org pages
- Align with the "Back to school campaign" around add-ons
- Explore opportunities to export the main marketing plans for US and Germany and provide them to community locally in market where we want to grow.

**Comment by couci** [comment]
Moving this under exploration

Since we are confident that this will be a campaign, I am turning this to an epic to track issues under it

**Comment by couci** [comment]
@nukeador I know you were preparing comms on that. What is the update?

**Comment by nukeador** [comment]
Still under exploration. We might do a light discourse conversation this/next week.

**Comment by couci** [comment]
@nukeador what is the plan with the discourse feedback? Are we planning to close this and send the first wave to the marketing team?
