### ISSUE TITLE
Write thank you page for playstore tool

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#59]
Since we are taking down the tool we need to replace the url with a thank you page

**Comment by couci** [comment]
Thank you for contributing to the support sprint.
With your contributions we managed to reply to 2203 reviews in 15 languages. That is amazing!

We are going to work on a second version of this tool based on your feedback and comments.

Interested in future campaigns? Follow our announcements here: https://discourse.mozilla.org/tags/mission-mozillians-campaigns

https://media.giphy.com/media/xsE65jaPsUKUo/giphy.gif

**Comment by couci** [comment]
@lucyeoh take a look, this will go on the support sprint website

**Comment by LucyeoH-zz** [comment]
Looks good
