### ISSUE TITLE
Write a MVP for activate site updates

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#62]
Capture what we want this time to do and what will it talk

**Comment by LucyeoH-zz** [comment]
Executive Brief:  https://docs.google.com/document/d/1g8vRddN4oAnyKWOisZJ7unsfrpiofTnjTigc9iMXvKo/edit

Content analysis: https://docs.google.com/document/d/1Drg4n0D6N5lk3DQNfq0_HDDoQO4OSEsXWu2tuZWbw8k/edit#
