### ISSUE TITLE
Webcompat Bug Triage (Evergreen?)

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#65]
## Project title: 
Webcompat Bug Triage (Evergreen?)

## Background:
Rosana finished a trial with the webcompat team about the value of volunteers pre-triaging bugs before they go to softvision. It turned out this additional screening is very helpful. However bugs come in relatively slowly over a long period of time making it not the best for fit a campaign, but possibly an evergreen area to explore. 

## Project Outline: 
Volunteers would help triage bgus. 

## Which of the high-impact areas will this campaign advance: 
Testing, Documentation
## What support do you need to be successful?:
Need to work closely with team to figure out what would make sense in this process.

**Comment by couci** [comment]
Talked with Rosana, we will turn this to an experiment for 10 people and if it works we will move it to evergreen contribution

Next task here: set email with Rosana and find contributors

**Comment by kelimuttu** [comment]
Application form has been closed. So far, we've got 18 applicants. 

Next: The webcompat team will take over for the selection process.

**Comment by couci** [comment]
@kelimuttu I guess we can close this one right?

**Comment by kelimuttu** [comment]
Yes (:
