### ISSUE TITLE
Get concrete next steps for Dark Funnel

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#69]
@LucyeoH to attend meeting and get concrete next steps

**Comment by LucyeoH-zz** [comment]
@couci we are ON for the campaign and they'd like it to start start of September (!!!) so we need to prioritize: 

- [x] Building a splash site (to be localized) 
- [x] Start writing copy for emails 
- [x] Add send dates to email calendar

Priority languages for localized sites & content (finalized in the meeting tmrw) EN-US, EN-CA and DE-DE - then... FR and TW

**Comment by couci** [comment]
@LucyeoH do we have a procedure on how people will be able to identify which of the websites are malicious and which are just unofficial?
Is there a database we will need to contribute to?

**Comment by LucyeoH-zz** [comment]
@couci this process will be an optional step for those who feel they can check the download safely. I believe we'll ask them to download but not execute the file and report the file name.

**Comment by couci** [comment]
closing this since the actions items here are a duplicate of #75
