### ISSUE TITLE
Write  and send comms for first emails that will go out

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#77]
- [x] Write Announcement Comms (due Aug 30th) @LucyeoH 
- [x] Write start planning Comms (due Aug 30th) @LucyeoH 
- [x] Send Announcement Comms (due Aug 31st) @couci 
- [x] Send start planning Comms on discourse and Reps general (due Sept 5th) @kelimuttu

**Comment by couci** [comment]
Comms to be reviewed by @yomanpatil

**Comment by couci** [comment]
@LucyeoH reminder here on translating

**Comment by kelimuttu** [comment]
@LucyeoH can you put me as assignee here as well?

**Comment by kelimuttu** [comment]
Is there any outstanding actions here?

**Comment by LucyeoH-zz** [comment]
@kelimuttu Kirby was going to come on one of the Reps call but I'm not sure how far coordination got. Can you find out if she's already attending (set it up if she isn't) and help promote that call?

**Comment by kelimuttu** [comment]
She was in the call yesterday. I worked on the comms & sent her a separate calender invite.

**Comment by LucyeoH-zz** [comment]
Great!
