### ISSUE TITLE
Translate campaign materials into Bahasa & Spanish

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#79]
### Translation Timeline

Total words to translate est. ~1450 throughout the campaign. 

The English copy will be updated here at or before the date listed below. 

**Reporting Form**
EST. words - 100 
- [x] [Final Copy in EN) (Friday, Sept 31st)  **READY NOW!** 
- [x] [Translated into ID](https://docs.google.com/document/d/1S3Atb1P-i8AkaV61A1QtMvrFuY6LpWwEuj9l1OBahfU/edit)
- [x] [Translated into ES](https://docs.google.com/document/d/1S3Atb1P-i8AkaV61A1QtMvrFuY6LpWwEuj9l1OBahfU/edit) (deadline - Sunday, Sept 2nd) 
- [x] Reporting Form Live (Monday, Sept 3rd) 

**Website Copy**
EST. words - 300 
- [x] Final Copy (Friday, Aug 31st) 
- [x] [Translated into ID](https://docs.google.com/document/d/1ZNjFX9ihyzbR51dXkyRHFjN8LHDQtkTgxwckO62QJYI/edit) (deadline - Sunday, Sept 2nd) 
- [x] [Translate into ES](https://docs.google.com/document/d/1uYUsAuvgG_Z1Nn8f3K7oGedFFJWlnGvhS4A4pTi3F4A/edit)(deadline - Sunday, Sept 2nd) 
- [x] Website Live on (live - Monday, Sept 3rd) 

**Email Copy** 
- [x] [Translate Announcement Email ](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)- ID
- [x] [Translate Announcement Email ](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)- ES (deadline - Sunday, Aug 2nd) 
- [x] [Start Planning Email - ID](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing) (deadline - Tuesday, Sept 4th) 
- [x] [Start Planning Email - ES](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing) (deadline - Tuesday, Sept 4th) 
- [x] [Reminder to Participate Email - ID](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Thursday, Sept 13th) 
- [x] [Reminder to Participate Email - ES](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Thursday, Sept 13th) 
- [x] [Participate! Email - ID](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Thursday, Sept 13th)  (deadline - Sunday, Sept 14th) 
- [x] [Participate! Email - ES](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Thursday, Sept 13th)  (deadline - Sunday, Sept 14th) 
- [x] [It's happening now! Email - ID](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Weds, Sept 17th) 
- [x] [It's happening now! Email - ES](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Weds, Sept 17th) 
- [x] [Thank you Email - ID](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Sunday, Sept 23rd) 
- [x] [Thank you Email - ES](https://docs.google.com/document/d/1TMS0_GgEzOrgNpM1MNT1Mk46wPq_qtlnKy5C35NylOc/edit?usp=sharing)(deadline - Sunday, Sept 23rd)

**Comment by kelimuttu** [comment]
Email draft for the localizer community has been made [here](https://drive.google.com/open?id=1ibJPUmPkNKfwpXvf5cSZMbYlLmqoAvJtIrFgUoCToj0).

**Comment by kelimuttu** [comment]
@LucyeoH can you put me as assignee as well?

**Comment by LucyeoH-zz** [comment]
New addition @kelimuttu and @nukeador there's a privacy in the form and a thank you page that need translation by Sept 7th (if possible): 

- [x] [Privacy Policy & Thank You](https://docs.google.com/document/d/1LTj3OFsXFJ7rSpCkZ2y8CjlcM5KVQOh6ktnnTsN9NgY/edit?usp=sharing) - ID
- [x] [Privacy Policy & Thank You](https://docs.google.com/document/d/1LTj3OFsXFJ7rSpCkZ2y8CjlcM5KVQOh6ktnnTsN9NgY/edit?usp=sharing) - ES

**Comment by nukeador** [comment]
Privacy Policy & Thank You done for ES

**Comment by rodin** [comment]
Privacy Policy & Thank You done for ID
