### ISSUE TITLE
Boosting mobile products at launch through review activity - for Focus/Klar

### ISSUE THREAD

**Issue by geroter** [mozilla/CampaignsforMDM#80]
## Project title: 
Boosting mobile products at launch through review activity - Sept 18th for Focus/Klar
## Project owner: 
TBD
## Stakeholders for Sign-Off: 
Connect with PMs and PMMs
## Background:
Specifically identified as important at both the Executive level (Mark Mayo) and PM level 
## Project Outline: 
Getting people to download/update new Focus/Klar that has GeckoView and rate it in the PlYStore within the first few days of launch ... very helpful for retention and acquisition
## Which of the high-impact areas will this campaign advance: 
Product evangelism
## What support do you need to be successful?:
Email activation. Maybe some ideas on how to incentivize/get recognition. 
## Project goal: 
* Desirable outcomes would be downloads/reviews within 48 hours of launch

## Timeline:
Very quick - Sept 18th

**Comment by LucyeoH-zz** [comment]
Send an email on the 17th (combined with final dark funnel detective email) to all Mozillians (not just vouched) and use a custom download link.

**Comment by LucyeoH-zz** [comment]
- Write email
- Get custom 
- Get referral link (@geroter to figure out)

**Comment by LucyeoH-zz** [comment]
2 emails - 1 ask per email
@geroter  to check exact timing of release

**Comment by LucyeoH-zz** [comment]
@lucyeoh to check if you can exclude vouched Mozillians.

**Comment by couci** [comment]
We are planning to use the 100k reactivated mailing list for this
@geroter do we have dates and a draft of what the comms will look like?

**Comment by geroter** [comment]
This is our unique link:
https://app.adjust.com/d2oqrsq?label=Post_Sept2018

**Comment by geroter** [comment]
Here's the overall Firefox Focus 7.0 release messaging that we can use to craft comms:
https://docs.google.com/presentation/d/1nMOI9gRulRiYiJCTHrcHdQ8-s2TBDGtaxFEyXQXuhaE/edit#slide=id.p

I don't have the GeckoView positioning doc in market, but hopefully we can take from this:
https://hacks.mozilla.org/2018/09/focus-with-geckoview/
https://wiki.mozilla.org/Mobile/GeckoView

We will need to run the comms by Loren Austin and Barbara Bermes for approval

**Comment by geroter** [comment]
Note: The current release date is around Oct 2nd. But that might change/be adjusted. As a result I think we should plan for email/comms/encouragement on Oct 4/5

**Comment by LucyeoH-zz** [comment]
Email download, review and share goes to 100k list

**Comment by LucyeoH-zz** [comment]
Need link to re-tweet or social copy
