### ISSUE TITLE
Add SUMO Sprint Emails to New Mailing List 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#81]
Upload the emails to [here](https://docs.google.com/spreadsheets/d/1v-YoFvIXQNhGyAwpl4QQ7IZWalGoLm4LVyGgVweEqp4/edit?ts=5b6db51d#gid=714059807). 

Also Guigs wants to take a look at them.

**Comment by couci** [comment]
list uploaded
