### ISSUE TITLE
Rocket Awareness Campaign

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#82]
Work with the Rocket team to run a country-targetted campaign to celebrate/announce the launch of Rocket in India.

**Comment by couci** [comment]
@LucyeoH what is the scope of this and what are the ongoing conversations? If there is no update will move it to backlog

**Comment by LucyeoH-zz** [comment]
Need to follow-up with Joe.

**Comment by LucyeoH-zz** [comment]
Awareness campaign set for Nov 1st - [executive brief ](https://docs.google.com/document/d/1HY-JjWUs4YAGDzm5MFF9JcOsScVZE_E_UW-8BG7QVMw/edit#)is locked to staff only for now b/c of non-public info.

**Comment by LucyeoH-zz** [comment]
This awareness campaign will only be in - India, Philippines, Thailand, Indonesia.
