### ISSUE TITLE
QA Campaign 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#83]
## Project title: 
Something with the QA team? 

## Project owner: 
<! -- Add the name of the person who is going to lead the project -->
## Stakeholders for Sign-Off: 
<! -- Add the names of staff that they to sign-off your project -->
## Outreach Plan:
<! --Indicate how are you planning to give visibility to your project and have volunteers to be engaged to participate. -->
## Project goal: 
<! -- Indicate what is the goal of your project, what is the desirable outcome. -->
* 
* 
* 
## Success metrics:
<! -- Set measurable metrics that you want to achieve by the end of this campaign. -->
## Timeline:
<! -- Create a reasonable timeline that includes all the steps of creating the campaign and the time that campaign runs -->
## Risk and dependencies:
<! -- Try to pre-dentify all the risks from your project plan and outside dependencies that might block your work -->
## Mitigation: 
<! -- Try to list all the actions you will take to minimize the risks -->

**Comment by couci** [comment]
There is no QA team in mozilla as a different team rather the QA people are part of products. @LucyeoH can you provide more info on which product we are considering of?

**Comment by iamVP7** [comment]
Hi @couci ,

Many times we are seeing contributors around Mozilla India & Bangladesh contributing to test days, beta days.  Is this different, they are following [QA website](https://quality.mozilla.org/)
