### ISSUE TITLE
Addons Localization Part 2 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/CampaignsforMDM#85]
## Project title: 
<! -- Write a short title that describes your project -->
## Project owner: 
<! -- Add the name of the person who is going to lead the project -->
## Stakeholders for Sign-Off: 
<! -- Add the names of staff that they to sign-off your project -->
## Outreach Plan:
<! --Indicate how are you planning to give visibility to your project and have volunteers to be engaged to participate. -->
## Project goal: 
<! -- Indicate what is the goal of your project, what is the desirable outcome. -->
* 
* 
* 
## Success metrics:
<! -- Set measurable metrics that you want to achieve by the end of this campaign. -->
## Timeline:
<! -- Create a reasonable timeline that includes all the steps of creating the campaign and the time that campaign runs -->
## Risk and dependencies:
<! -- Try to pre-dentify all the risks from your project plan and outside dependencies that might block your work -->
## Mitigation: 
<! -- Try to list all the actions you will take to minimize the risks -->

**Comment by couci** [comment]
@LucyeoH what is the scope of this? are we planning to run the same locals twice or are we expanding to other locals. 
@nukeador did the marketing phase run? Do we have results to see if this was successful?

**Comment by nukeador** [comment]
Promotion phase hasn't happened yet, we are waiting.

**Comment by couci** [comment]
@nukeador should we close this one? what is the status

**Comment by nukeador** [comment]
We should close, this was the internal report for the v2

https://docs.google.com/document/d/1goWGrMgTi-H0nz_Ew6-7UzoldYy_cxPLvUp076MUemU/edit?pli=1#

We de-prioritized a v2 of the campaign.
