### ISSUE TITLE
Pocket parser crowdsourcing

### ISSUE THREAD

**Issue by nukeador** [mozilla/CampaignsforMDM#91]
Pocket parser for urls needs a lot of love, specially for domains not very well known.

We could use our crowdsourcing powers to deliver value here.

[Current internal exploration](https://docs.google.com/document/d/1Vv0m0mLvIuh0ZuDLPDbssaVMZnytAlY1pXzdpu2Fhy8/edit#heading=h.wwrppy1k8k3v)

**Comment by couci** [comment]
@nukeador is this connected with #51 ?

**Comment by nukeador** [comment]
Not connected

**Comment by nukeador** [comment]
Meeting happened, updated internal doc link.

**Comment by couci** [comment]
this is moving back to backlog, we are going to revisit it
