### ISSUE TITLE
Create a review process (community reccomendation score process)

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#96]
- [x] align with pocket team
- [x] figure out data collection policy
- [x] create a hacky system for people to score

**Comment by nukeador** [comment]
WIP https://docs.google.com/document/d/1XZzefiH8ekitWqJixso60phkB5efGwZdhJeiuZq2yBI/edit#

**Comment by couci** [comment]
base questions are agreed

**Comment by couci** [comment]
data collection is tracked on legal issue, draft system created, will be tested with the rest of the team on the 27th of December
